# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
default: &default
  starladder_application_id: 957c3669c5ec514fe0b895f9555f5eadda2fbaf5d5757a4a8c926d4f02b013f9
  starladder_secret: ddddc41aa306efd9361b5769bdafabc2d273e78af40cc3ba47b54eb9bd631f59

development:
  <<: *default
  secret_key_base: 76efc116582f8108d14f14d1d9cb95aab74e873574e646528a426a968789abad61da1275b54ac10ba0ee562598610da13b075b43d511d4e94f835bac08e0571b

test:
  secret_key_base: ece7597882fc9483b3aa4ca67cb2a856d7d4ec9e956b741009e3830fb12151c9cefa4522c9e673736aaa7a56c2e97145df1f9949ba18cabb55a3a20e96218cef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
